Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
model.save("solubility-rnn-accurate")
# model = tf.keras.models.load_model('solubility-rnn-accurate/')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[11], line 1[0m
[0;32m----> 1[0m [43mmodel[49m[38;5;241;43m.[39;49m[43msave[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43msolubility-rnn-accurate[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m [38;5;66;03m# model = tf.keras.models.load_model('solubility-rnn-accurate/')[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py:122[0m, in [0;36mfilter_traceback.<locals>.error_handler[0;34m(*args, **kwargs)[0m
[1;32m    119[0m     filtered_tb [38;5;241m=[39m _process_traceback_frames(e[38;5;241m.[39m__traceback__)
[1;32m    120[0m     [38;5;66;03m# To get the full stack trace, call:[39;00m
[1;32m    121[0m     [38;5;66;03m# `keras.config.disable_traceback_filtering()`[39;00m
[0;32m--> 122[0m     [38;5;28;01mraise[39;00m e[38;5;241m.[39mwith_traceback(filtered_tb) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m
[1;32m    123[0m [38;5;28;01mfinally[39;00m:
[1;32m    124[0m     [38;5;28;01mdel[39;00m filtered_tb

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/keras/src/saving/saving_api.py:114[0m, in [0;36msave_model[0;34m(model, filepath, overwrite, zipped, **kwargs)[0m
[1;32m    110[0m [38;5;28;01mif[39;00m [38;5;28mstr[39m(filepath)[38;5;241m.[39mendswith(([38;5;124m"[39m[38;5;124m.h5[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m.hdf5[39m[38;5;124m"[39m)):
[1;32m    111[0m     [38;5;28;01mreturn[39;00m legacy_h5_format[38;5;241m.[39msave_model_to_hdf5(
[1;32m    112[0m         model, filepath, overwrite, include_optimizer
[1;32m    113[0m     )
[0;32m--> 114[0m [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    115[0m     [38;5;124m"[39m[38;5;124mInvalid filepath extension for saving. [39m[38;5;124m"[39m
[1;32m    116[0m     [38;5;124m"[39m[38;5;124mPlease add either a `.keras` extension for the native Keras [39m[38;5;124m"[39m
[1;32m    117[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124mformat (recommended) or a `.h5` extension. [39m[38;5;124m"[39m
[1;32m    118[0m     [38;5;124m"[39m[38;5;124mUse `model.export(filepath)` if you want to export a SavedModel [39m[38;5;124m"[39m
[1;32m    119[0m     [38;5;124m"[39m[38;5;124mfor use with TFLite/TFServing/etc. [39m[38;5;124m"[39m
[1;32m    120[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124mReceived: filepath=[39m[38;5;132;01m{[39;00mfilepath[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m"[39m
[1;32m    121[0m )

[0;31mValueError[0m: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=solubility-rnn-accurate.

